// <auto-generated />
namespace SMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newsaltpropertyintraderclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsaltpropertyintraderclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201705030524589_new salt property in trader class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
