// <auto-generated />
namespace SMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dateSoldtoOptional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateSoldtoOptional));
        
        string IMigrationMetadata.Id
        {
            get { return "201704232054206_dateSold to Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
